name: Docker Build, Push and Deploy

on:
  push:
    branches: [main]
    # Nur bestimmte Dateien auslösen (optional)
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'next.config.ts'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Semantische Versionierung basierend auf Tags (optional)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: blisha234/sascha-kohler-website
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=blisha234/sascha-kohler-website:buildcache
          cache-to: type=registry,ref=blisha234/sascha-kohler-website:buildcache,mode=max
# name: Build and Push Container
#
# on:
#   push:
#     branches: [main]
#   workflow_dispatch: # Allows manual triggering
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           tags: ghcr.io/saschakohler/sascha-kohler-website:latest
