name: Docker Build, Push and Deploy

on:
  push:
    branches: [main]
    # Nur bestimmte Dateien auslösen (optional)
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'next.config.ts'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Semantische Versionierung basierend auf Tags (optional)
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: blisha234/sascha-kohler-website
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=blisha234/sascha-kohler-website:buildcache
          cache-to: type=registry,ref=blisha234/sascha-kohler-website:buildcache,mode=max
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to k3s
        run: |
          # Rollout restart des Deployments im richtigen Namespace
          kubectl rollout restart deployment/sascha-kohler-website -n sascha-kohler-at

          # Warte auf erfolgreichen Rollout
          kubectl rollout status deployment/sascha-kohler-website -n sascha-kohler-at
